INSERT INTO Productos(nombre) VALUES ('Aceite');
INSERT INTO Productos(nombre) VALUES ('Aceitunas');
INSERT INTO Productos(nombre) VALUES ('Acelga');
INSERT INTO Productos(nombre) VALUES ('Acondicionador');
INSERT INTO Productos(nombre) VALUES ('Aderezo Alioli');
INSERT INTO Productos(nombre) VALUES ('Aderezo Barbacoa');
INSERT INTO Productos(nombre) VALUES ('Aderezo Ketchup');
INSERT INTO Productos(nombre) VALUES ('Aderezo Mayonesa');
INSERT INTO Productos(nombre) VALUES ('Aderezo Mostaza');
INSERT INTO Productos(nombre) VALUES ('Aderezo Mostaza Con Miel');
INSERT INTO Productos(nombre) VALUES ('Aderezo Salsa cesar');
INSERT INTO Productos(nombre) VALUES ('Agua mineral');
INSERT INTO Productos(nombre) VALUES ('Algodón');
INSERT INTO Productos(nombre) VALUES ('Ananá');
INSERT INTO Productos(nombre) VALUES ('Arroz');
INSERT INTO Productos(nombre) VALUES ('Arvejas en lata');
INSERT INTO Productos(nombre) VALUES ('Atún en lata');
INSERT INTO Productos(nombre) VALUES ('Azúcar');
INSERT INTO Productos(nombre) VALUES ('Banana');
INSERT INTO Productos(nombre) VALUES ('Batata');
INSERT INTO Productos(nombre) VALUES ('Bifes');
INSERT INTO Productos(nombre) VALUES ('Bizcochos');
INSERT INTO Productos(nombre) VALUES ('Bolsas para basura');
INSERT INTO Productos(nombre) VALUES ('Botella de tomate');
INSERT INTO Productos(nombre) VALUES ('Cacao');
INSERT INTO Productos(nombre) VALUES ('Café Latte');
INSERT INTO Productos(nombre) VALUES ('Café instantáneo');
INSERT INTO Productos(nombre) VALUES ('Capeletinis');
INSERT INTO Productos(nombre) VALUES ('Capuchino');
INSERT INTO Productos(nombre) VALUES ('Carne picada común');
INSERT INTO Productos(nombre) VALUES ('Carne picada especial');
INSERT INTO Productos(nombre) VALUES ('Cepillo de dientes');
INSERT INTO Productos(nombre) VALUES ('Cereales de chocolate');
INSERT INTO Productos(nombre) VALUES ('Cereales de maíz');
INSERT INTO Productos(nombre) VALUES ('Cerveza');
INSERT INTO Productos(nombre) VALUES ('Choclo en lata');
INSERT INTO Productos(nombre) VALUES ('Chocolate en barra');
INSERT INTO Productos(nombre) VALUES ('Ciruelas');
INSERT INTO Productos(nombre) VALUES ('Coca Cola');
INSERT INTO Productos(nombre) VALUES ('Crema de leche chica');
INSERT INTO Productos(nombre) VALUES ('Crema de leche grande');
INSERT INTO Productos(nombre) VALUES ('Deshodorante');
INSERT INTO Productos(nombre) VALUES ('Desinfectante para pisos');
INSERT INTO Productos(nombre) VALUES ('Dulce de leche chico');
INSERT INTO Productos(nombre) VALUES ('Dulce de leche grande');
INSERT INTO Productos(nombre) VALUES ('Durazno en Lata');
INSERT INTO Productos(nombre) VALUES ('Edulcorante');
INSERT INTO Productos(nombre) VALUES ('Esencia de vainilla');
INSERT INTO Productos(nombre) VALUES ('Espinaca');
INSERT INTO Productos(nombre) VALUES ('Esponja');
INSERT INTO Productos(nombre) VALUES ('Esponja acero');
INSERT INTO Productos(nombre) VALUES ('Facturas');
INSERT INTO Productos(nombre) VALUES ('Fiambre Jamón y Queso');
INSERT INTO Productos(nombre) VALUES ('Fiambre jamón');
INSERT INTO Productos(nombre) VALUES ('Fiambre salame');
INSERT INTO Productos(nombre) VALUES ('Fiambres varios');
INSERT INTO Productos(nombre) VALUES ('Fideo Cabello de Angel');
INSERT INTO Productos(nombre) VALUES ('Fideo codito');
INSERT INTO Productos(nombre) VALUES ('Fideo mostachol');
INSERT INTO Productos(nombre) VALUES ('Fideo moñito');
INSERT INTO Productos(nombre) VALUES ('Fideo munición');
INSERT INTO Productos(nombre) VALUES ('Fideo spaguetti');
INSERT INTO Productos(nombre) VALUES ('Fideo tirabuzón');
INSERT INTO Productos(nombre) VALUES ('Frutilla');
INSERT INTO Productos(nombre) VALUES ('Frutilla en lata');
INSERT INTO Productos(nombre) VALUES ('Garbanzos en lata');
INSERT INTO Productos(nombre) VALUES ('Hamburgesas de carne');
INSERT INTO Productos(nombre) VALUES ('Hamburgesas de pollo');
INSERT INTO Productos(nombre) VALUES ('Harina');
INSERT INTO Productos(nombre) VALUES ('Huevos');
INSERT INTO Productos(nombre) VALUES ('Jabón Líquido');
INSERT INTO Productos(nombre) VALUES ('Jabón de baño');
INSERT INTO Productos(nombre) VALUES ('Jugo en polvo');
INSERT INTO Productos(nombre) VALUES ('Lavandina');
INSERT INTO Productos(nombre) VALUES ('Leche');
INSERT INTO Productos(nombre) VALUES ('Leche condensada');
INSERT INTO Productos(nombre) VALUES ('Leche en polvo');
INSERT INTO Productos(nombre) VALUES ('Lechuga');
INSERT INTO Productos(nombre) VALUES ('Lentejas en lata');
INSERT INTO Productos(nombre) VALUES ('Mandarina');
INSERT INTO Productos(nombre) VALUES ('Manteca');
INSERT INTO Productos(nombre) VALUES ('Mantequilla de maní');
INSERT INTO Productos(nombre) VALUES ('Manzana');
INSERT INTO Productos(nombre) VALUES ('Masitas Oreo');
INSERT INTO Productos(nombre) VALUES ('Masitas Pamela');
INSERT INTO Productos(nombre) VALUES ('Masitas Vainilla');
INSERT INTO Productos(nombre) VALUES ('Masitas de agua');
INSERT INTO Productos(nombre) VALUES ('Mate Cocido');
INSERT INTO Productos(nombre) VALUES ('Medallones de pollo');
INSERT INTO Productos(nombre) VALUES ('Mermelada de ciruela');
INSERT INTO Productos(nombre) VALUES ('Mermelada de durazno');
INSERT INTO Productos(nombre) VALUES ('Mermelada de frutilla');
INSERT INTO Productos(nombre) VALUES ('Miel');
INSERT INTO Productos(nombre) VALUES ('Milanesa de carne');
INSERT INTO Productos(nombre) VALUES ('Milanesa de pollo');
INSERT INTO Productos(nombre) VALUES ('Milanesa de soja');
INSERT INTO Productos(nombre) VALUES ('Minerva');
INSERT INTO Productos(nombre) VALUES ('Naranjas');
INSERT INTO Productos(nombre) VALUES ('Pan común');
INSERT INTO Productos(nombre) VALUES ('Pan de hamburguesas');
INSERT INTO Productos(nombre) VALUES ('Pan de pancho');
INSERT INTO Productos(nombre) VALUES ('Pan lactal');
INSERT INTO Productos(nombre) VALUES ('Pan rallado');
INSERT INTO Productos(nombre) VALUES ('Papas');
INSERT INTO Productos(nombre) VALUES ('Papel higiénico');
INSERT INTO Productos(nombre) VALUES ('Paso de los Toros');
INSERT INTO Productos(nombre) VALUES ('Pasta de dientes');
INSERT INTO Productos(nombre) VALUES ('Patitas de pollo');
INSERT INTO Productos(nombre) VALUES ('Pechuga de pollo');
INSERT INTO Productos(nombre) VALUES ('Pepinillos');
INSERT INTO Productos(nombre) VALUES ('Pimiento');
INSERT INTO Productos(nombre) VALUES ('Polenta');
INSERT INTO Productos(nombre) VALUES ('Porotos en lata');
INSERT INTO Productos(nombre) VALUES ('Postre de vainilla');
INSERT INTO Productos(nombre) VALUES ('Premezcla para bizcochuelo');
INSERT INTO Productos(nombre) VALUES ('Premezcla para chipa');
INSERT INTO Productos(nombre) VALUES ('Premezcla para pizza');
INSERT INTO Productos(nombre) VALUES ('Puré de tomate');
INSERT INTO Productos(nombre) VALUES ('Queso crema');
INSERT INTO Productos(nombre) VALUES ('Queso cremoso');
INSERT INTO Productos(nombre) VALUES ('Queso en barra');
INSERT INTO Productos(nombre) VALUES ('Repelente');
INSERT INTO Productos(nombre) VALUES ('Repollo');
INSERT INTO Productos(nombre) VALUES ('Repollo colorado');
INSERT INTO Productos(nombre) VALUES ('Sal');
INSERT INTO Productos(nombre) VALUES ('Salchichas');
INSERT INTO Productos(nombre) VALUES ('Salsa lista');
INSERT INTO Productos(nombre) VALUES ('Servilleta de papel');
INSERT INTO Productos(nombre) VALUES ('Shampoo');
INSERT INTO Productos(nombre) VALUES ('Sopas');
INSERT INTO Productos(nombre) VALUES ('Sprite');
INSERT INTO Productos(nombre) VALUES ('Talco');
INSERT INTO Productos(nombre) VALUES ('Tapas para empanada');
INSERT INTO Productos(nombre) VALUES ('Tapas para tarta');
INSERT INTO Productos(nombre) VALUES ('Te');
INSERT INTO Productos(nombre) VALUES ('Tomate');
INSERT INTO Productos(nombre) VALUES ('Tortilla de trigo');
INSERT INTO Productos(nombre) VALUES ('Trapo de piso');
INSERT INTO Productos(nombre) VALUES ('Uvas');
INSERT INTO Productos(nombre) VALUES ('Vinagre');
INSERT INTO Productos(nombre) VALUES ('Yerba');
INSERT INTO Productos(nombre) VALUES ('Yogurt');
INSERT INTO Productos(nombre) VALUES ('Yogurt Bebible');
INSERT INTO Productos(nombre) VALUES ('Zanahoria');
INSERT INTO Productos(nombre) VALUES ('Zapallito');
INSERT INTO Productos(nombre) VALUES ('Zapallo');
